name: flutter_nop
description: state manager, dependencies manager
version: 2.0.0
repository: https://github.com/sersr/nop_flutter

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  nop: ^0.0.2+1
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0