name: flutter_nop
description: state manager, dependencies manager
version: 2.1.4
repository: https://github.com/sersr/flutter_nop

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  nop: ">=0.0.3+1 <1.0.0"
  equatable: ">=2.0.3 <3.0.0"
  collection: ">=1.15.0 <2.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  nop_gen: ^0.2.1
  nop_annotations: ^0.2.0
  build_runner: any

dependency_overrides:
  nop_gen:
    path: ../nop_gen
  nop_annotations:
    path: ../nop_annotations
